# -*- coding: utf-8 -*-
"""Fuente única de verdad de la matriz de casos de prueba del módulo PIM.

Los tres entregables (02-casos-de-prueba.md, .csv y .xlsx) se generan desde
aquí con `python tools/generar-matriz.py`, de modo que no puedan divergir.
"""

# id, requisito, título, precondiciones, pasos, datos, esperado,
# prioridad, tipo, técnica, estado, defecto
CASOS = [
    # ---------------------------------------------------------------- Add Employee
    (
        "CP-001", "RF-01, RF-09",
        "Alta de empleado con los datos mínimos obligatorios",
        "Sesión iniciada como Admin.",
        ["Ir a PIM > Add Employee.",
         "Introducir First Name y Last Name.",
         "Dejar «Create Login Details» desactivado.",
         "Pulsar Save."],
        "First Name: Lucía · Last Name: Herrera",
        "El empleado se crea, aparece el aviso «Successfully Saved» y la aplicación "
        "redirige a la ficha del empleado con el Employee Id asignado.",
        "Alta", "Funcional / Smoke", "Tabla de decisión (R1)", "Pasa", "",
    ),
    (
        "CP-002", "RF-01",
        "El alta sin First Name se rechaza",
        "Sesión iniciada como Admin.",
        ["Ir a PIM > Add Employee.",
         "Dejar First Name vacío e introducir solo Last Name.",
         "Pulsar Save."],
        "First Name: (vacío) · Last Name: Herrera",
        "El empleado no se crea y aparece el mensaje «Required» bajo el campo First Name.",
        "Alta", "Funcional negativo", "Tabla de decisión (R2)", "Pasa", "",
    ),
    (
        "CP-003", "RF-01",
        "El alta sin Last Name se rechaza",
        "Sesión iniciada como Admin.",
        ["Ir a PIM > Add Employee.",
         "Introducir solo First Name.",
         "Pulsar Save."],
        "First Name: Lucía · Last Name: (vacío)",
        "El empleado no se crea y aparece el mensaje «Required» bajo el campo Last Name.",
        "Media", "Funcional negativo", "Particiones de equivalencia", "Pasa", "",
    ),
    (
        "CP-004", "RF-02",
        "First Name admite exactamente 30 caracteres (límite superior)",
        "Sesión iniciada como Admin.",
        ["Ir a PIM > Add Employee.",
         "Pegar en First Name una cadena de 30 caracteres.",
         "Introducir un Last Name válido.",
         "Pulsar Save y abrir la ficha creada."],
        "First Name: Abcdefghijklmnopqrstuvwxyzabcd (30) · Last Name: Herrera",
        "El empleado se crea y el nombre se almacena y se muestra completo, sin truncar.",
        "Media", "Funcional positivo", "Valores límite", "Pasa", "",
    ),
    (
        "CP-005", "RF-02",
        "First Name no admite 31 caracteres (límite superior + 1)",
        "Sesión iniciada como Admin.",
        ["Ir a PIM > Add Employee.",
         "Pegar en First Name una cadena de 31 caracteres.",
         "Observar el contenido del campo.",
         "Pulsar Save."],
        "First Name: Abcdefghijklmnopqrstuvwxyzabcde (31)",
        "El campo impide superar los 30 caracteres o el sistema muestra un error de "
        "longitud. En ningún caso se guarda un valor truncado en silencio.",
        "Media", "Funcional negativo", "Valores límite", "Pasa", "",
    ),
    (
        "CP-006", "RF-04",
        "El alta con un Employee Id ya existente se rechaza",
        "Sesión iniciada como Admin. Existe un empleado con Employee Id conocido.",
        ["Anotar el Employee Id de un empleado existente desde PIM > Employee List.",
         "Ir a PIM > Add Employee.",
         "Introducir nombre y apellido válidos.",
         "Sustituir el Employee Id autogenerado por el anotado en el paso 1.",
         "Pulsar Save."],
        "Employee Id: (uno ya existente en el listado)",
        "El empleado no se crea y se muestra un mensaje indicando que el Employee Id "
        "ya está en uso.",
        "Alta", "Funcional negativo", "Tabla de decisión (R3)", "Pasa", "",
    ),
    (
        "CP-007", "RF-01",
        "El alta con nombres compuestos solo por espacios en blanco se rechaza",
        "Sesión iniciada como Admin.",
        ["Ir a PIM > Add Employee.",
         "Introducir tres espacios en First Name y tres en Last Name.",
         "Pulsar Save."],
        "First Name: «   » · Last Name: «   »",
        "El sistema trata los campos como vacíos y muestra «Required». No se crea un "
        "empleado sin nombre visible en el listado.",
        "Media", "Funcional negativo", "Conjetura de errores", "Pasa", "",
    ),
    (
        "CP-008", "RF-01",
        "Los campos de nombre no admiten dígitos ni caracteres especiales",
        "Sesión iniciada como Admin.",
        ["Ir a PIM > Add Employee.",
         "Introducir en First Name una cadena numérica y en Last Name símbolos.",
         "Pulsar Save.",
         "Volver a PIM > Employee List y localizar el registro."],
        "First Name: 12345 · Last Name: !@#$%^&*()",
        "El sistema rechaza la entrada con un mensaje de validación de formato: un "
        "nombre de persona no admite dígitos ni símbolos.",
        "Media", "Funcional negativo", "Particiones de equivalencia", "Falla", "BUG-001",
    ),
    (
        "CP-009", "RF-05",
        "La foto de perfil por encima de 1 MB se rechaza",
        "Sesión iniciada como Admin. Fichero de imagen de ~1,2 MB disponible.",
        ["Ir a PIM > Add Employee.",
         "Pulsar sobre el área de la foto y seleccionar el fichero de 1,2 MB.",
         "Introducir nombre y apellido válidos.",
         "Pulsar Save."],
        "Fichero: foto-1200kb.jpg (1,2 MB)",
        "El sistema rechaza el fichero indicando que se supera el tamaño máximo "
        "permitido, y no crea el empleado con una foto inválida.",
        "Media", "Funcional negativo", "Valores límite", "Pasa", "",
    ),
    (
        "CP-010", "RF-06, RF-07, RF-08",
        "Alta de empleado con credenciales de acceso válidas",
        "Sesión iniciada como Admin.",
        ["Ir a PIM > Add Employee.",
         "Introducir nombre y apellido válidos.",
         "Activar «Create Login Details».",
         "Introducir usuario y contraseña que cumplen la política, estado Enabled.",
         "Pulsar Save.",
         "Comprobar en Admin > User Management que el usuario aparece."],
        "Usuario: dcoya.test01 · Contraseña: Test1234",
        "El empleado se crea con su usuario asociado y este figura en la lista de "
        "usuarios del sistema con estado Enabled.",
        "Alta", "Funcional positivo", "Tabla de decisión (R4)", "Pasa", "",
    ),
    (
        "CP-011", "RF-08, RF-09",
        "Una contraseña que incumple la política no debe dejar el empleado creado",
        "Sesión iniciada como Admin.",
        ["Ir a PIM > Add Employee.",
         "Introducir nombre y apellido válidos.",
         "Activar «Create Login Details».",
         "Introducir un usuario válido y la contraseña «test» (incumple la política).",
         "Pulsar Save.",
         "Ir a PIM > Employee List y buscar el nombre introducido."],
        "Usuario: dcoya.test02 · Contraseña: test",
        "El formulario muestra el error de política de contraseña y NO se crea el "
        "empleado: la operación es atómica.",
        "Alta", "Funcional negativo", "Tabla de decisión (R5)", "Falla", "BUG-002",
    ),
    (
        "CP-012", "RF-07",
        "El nombre de usuario por debajo de 5 caracteres se rechaza",
        "Sesión iniciada como Admin.",
        ["Ir a PIM > Add Employee.",
         "Introducir nombre y apellido válidos.",
         "Activar «Create Login Details».",
         "Introducir un usuario de 4 caracteres y una contraseña válida.",
         "Pulsar Save."],
        "Usuario: dcoy (4 caracteres) · Contraseña: Test1234",
        "El sistema muestra el mensaje de longitud mínima del nombre de usuario y no "
        "crea el registro.",
        "Media", "Funcional negativo", "Valores límite", "Pasa", "",
    ),
    # ---------------------------------------------------------------- Employee List
    (
        "CP-013", "RF-10",
        "Búsqueda de empleado por Employee Id exacto",
        "Sesión iniciada como Admin. Existe un empleado con Employee Id conocido.",
        ["Ir a PIM > Employee List.",
         "Introducir el Employee Id en el campo correspondiente.",
         "Pulsar Search."],
        "Employee Id: (el del empleado creado en CP-001)",
        "El listado devuelve únicamente el empleado con ese identificador y el "
        "contador indica «(1) Record Found».",
        "Alta", "Funcional / Smoke", "Particiones de equivalencia", "Pasa", "",
    ),
    (
        "CP-014", "RF-11",
        "El autocompletado de Employee Name sugiere a partir del tercer carácter",
        "Sesión iniciada como Admin.",
        ["Ir a PIM > Employee List.",
         "Escribir dos caracteres en Employee Name y esperar.",
         "Escribir un tercer carácter y esperar."],
        "Texto: «Lu» y después «Luc»",
        "Con dos caracteres no se despliegan sugerencias; con tres aparece la lista "
        "de coincidencias.",
        "Media", "Funcional positivo", "Valores límite", "Pasa", "",
    ),
    (
        "CP-015", "RF-11",
        "Búsqueda con texto parcial válido sin seleccionar sugerencia",
        "Sesión iniciada como Admin. Existe al menos un empleado cuyo nombre empieza por «Luc».",
        ["Ir a PIM > Employee List.",
         "Escribir «Luc» en Employee Name sin pulsar ninguna sugerencia.",
         "Pulsar Search."],
        "Texto: Luc",
        "El sistema busca por coincidencia parcial y devuelve los empleados cuyo "
        "nombre contiene el texto, o bien indica con claridad que debe elegirse una "
        "sugerencia. No debe etiquetarse como «Invalid» un dato correcto.",
        "Media", "Usabilidad", "Conjetura de errores", "Falla", "BUG-003",
    ),
    (
        "CP-016", "RF-12",
        "El filtro combinado aplica conjunción lógica entre criterios",
        "Sesión iniciada como Admin.",
        ["Ir a PIM > Employee List.",
         "Seleccionar una Sub Unit con varios empleados.",
         "Seleccionar además un Employment Status.",
         "Pulsar Search.",
         "Revisar las columnas del resultado."],
        "Sub Unit: Engineering · Employment Status: Full-Time Permanent",
        "Todos los registros devueltos cumplen simultáneamente los dos criterios; "
        "ninguno cumple solo uno.",
        "Alta", "Funcional positivo", "Tabla de decisión", "Pasa", "",
    ),
    (
        "CP-017", "RF-16",
        "Búsqueda sin coincidencias muestra «No Records Found»",
        "Sesión iniciada como Admin.",
        ["Ir a PIM > Employee List.",
         "Introducir un Employee Id inexistente.",
         "Pulsar Search."],
        "Employee Id: ZZ999999",
        "Se muestra el aviso «No Records Found», la tabla queda vacía y la cabecera "
        "y los filtros siguen operativos.",
        "Media", "Funcional negativo", "Particiones de equivalencia", "Pasa", "",
    ),
    (
        "CP-018", "RF-13",
        "El botón Reset limpia todos los filtros y restaura el listado",
        "Sesión iniciada como Admin. Hay una búsqueda filtrada aplicada.",
        ["Aplicar un filtro por Sub Unit y otro por Employment Status.",
         "Pulsar Search y comprobar que el listado se reduce.",
         "Pulsar Reset."],
        "—",
        "Todos los campos de filtro vuelven a su valor por defecto y el listado "
        "muestra de nuevo el total de empleados.",
        "Alta", "Funcional / Smoke", "Transición de estados", "Pasa", "",
    ),
    (
        "CP-019", "RF-14, RF-17",
        "Al eliminar el último registro de la última página el listado se reubica",
        "Sesión iniciada como Admin. El listado tiene más de una página y la última "
        "contiene un único registro eliminable creado para la prueba.",
        ["Ir a PIM > Employee List.",
         "Navegar hasta la última página de la paginación.",
         "Eliminar el único registro que contiene y confirmar.",
         "Observar el listado resultante."],
        "—",
        "Tras el borrado la aplicación retrocede a la página anterior y muestra "
        "registros. No debe quedar una tabla vacía con un total mayor que cero.",
        "Media", "Funcional negativo", "Valores límite", "Falla", "BUG-004",
    ),
    (
        "CP-020", "RF-15",
        "La ordenación por columna se mantiene al cambiar de página",
        "Sesión iniciada como Admin. El listado tiene más de una página.",
        ["Ir a PIM > Employee List.",
         "Ordenar por Last Name en orden ascendente.",
         "Comprobar el orden de la primera página.",
         "Avanzar a la página siguiente y comprobar el orden."],
        "Columna: Last Name (A-Z)",
        "El criterio de ordenación persiste entre páginas y la secuencia alfabética "
        "continúa de forma coherente de una página a la siguiente.",
        "Baja", "Funcional", "Transición de estados", "Falla", "BUG-005",
    ),
    (
        "CP-021", "RF-17",
        "Borrado múltiple de empleados con confirmación previa",
        "Sesión iniciada como Admin. Existen al menos dos empleados de prueba.",
        ["Ir a PIM > Employee List.",
         "Marcar la casilla de dos empleados de prueba.",
         "Pulsar «Delete Selected».",
         "Confirmar en el diálogo.",
         "Buscar de nuevo ambos empleados."],
        "Empleados creados en CP-001 y CP-004",
        "Se solicita confirmación antes de borrar, ambos registros desaparecen del "
        "listado y una búsqueda posterior no los devuelve.",
        "Alta", "Funcional positivo", "Transición de estados", "Pasa", "",
    ),
    # ---------------------------------------------------------------- Personal Details
    (
        "CP-022", "RF-18, RF-22",
        "Edición y guardado de los datos personales de un empleado",
        "Sesión iniciada como Admin. Existe el empleado de prueba.",
        ["Abrir la ficha del empleado desde PIM > Employee List.",
         "En Personal Details modificar Other Id, Nationality y Marital Status.",
         "Pulsar Save.",
         "Recargar la página."],
        "Other Id: OT-0091 · Nationality: Spanish · Marital Status: Single",
        "Aparece «Successfully Updated» y los tres valores se conservan tras recargar "
        "la página.",
        "Alta", "Funcional positivo", "Particiones de equivalencia", "Pasa", "",
    ),
    (
        "CP-023", "RF-19, RF-20",
        "La fecha de nacimiento con formato inválido se rechaza",
        "Sesión iniciada como Admin. Ficha de empleado abierta.",
        ["Situarse en Personal Details.",
         "Escribir manualmente una fecha con formato incorrecto en Date of Birth.",
         "Pulsar Save."],
        "Date of Birth: 31/02/2020",
        "Se muestra el mensaje «Should be a valid date in yyyy-dd-mm format» y el "
        "valor no se guarda.",
        "Media", "Funcional negativo", "Particiones de equivalencia", "Pasa", "",
    ),
    (
        "CP-024", "RN-01",
        "La fecha de nacimiento no admite fechas futuras",
        "Sesión iniciada como Admin. Ficha de empleado abierta.",
        ["Situarse en Personal Details.",
         "Abrir el selector de Date of Birth y navegar hasta un año futuro.",
         "Seleccionar una fecha posterior a hoy.",
         "Pulsar Save."],
        "Date of Birth: 2035-01-01",
        "El sistema rechaza la fecha con un mensaje de validación: una fecha de "
        "nacimiento posterior a hoy no es un dato posible.",
        "Alta", "Funcional negativo", "Conjetura de errores", "Falla", "BUG-006",
    ),
    (
        "CP-025", "RF-18, RN-04",
        "Permiso de conducir con fecha de caducidad pasada",
        "Sesión iniciada como Admin. Ficha de empleado abierta.",
        ["Situarse en Personal Details.",
         "Introducir número de licencia y una fecha de caducidad anterior a hoy.",
         "Pulsar Save y recargar."],
        "License Number: B-4457821 · Expiry Date: 2019-01-15",
        "El dato se guarda —es un valor histórico legítimo— y el sistema no lo trata "
        "como error de validación.",
        "Baja", "Funcional positivo", "Particiones de equivalencia", "Pasa", "",
    ),
    (
        "CP-026", "RF-22",
        "Los cambios en la ficha se reflejan en el listado de empleados",
        "Sesión iniciada como Admin. Existe el empleado de prueba.",
        ["Modificar el Last Name del empleado desde su ficha y guardar.",
         "Ir a PIM > Employee List.",
         "Buscar el empleado por su Employee Id."],
        "Last Name: Herrera → Herrera-Ruiz",
        "El listado muestra el apellido actualizado sin necesidad de vaciar la caché "
        "ni volver a iniciar sesión.",
        "Alta", "Funcional / Smoke", "Transición de estados", "Pasa", "",
    ),
    (
        "CP-027", "RF-10, RF-18",
        "Nombres con tildes y caracteres no ASCII: guardado y búsqueda",
        "Sesión iniciada como Admin.",
        ["Crear un empleado con acentos en el nombre.",
         "Comprobar que la ficha y el listado los muestran correctamente.",
         "Buscar el empleado escribiendo el nombre SIN tildes.",
         "Buscar el empleado escribiendo el nombre CON tildes."],
        "First Name: Mónica · Last Name: Núñez",
        "El nombre se almacena y se muestra sin corrupción de caracteres, y la "
        "búsqueda lo encuentra tanto con tildes como sin ellas.",
        "Media", "Funcional", "Particiones de equivalencia", "Falla", "BUG-007",
    ),
    (
        "CP-028", "RF-18, RNF-02",
        "El contenido con etiquetas HTML se escapa al mostrarse",
        "Sesión iniciada como Admin.",
        ["Crear un empleado cuyo First Name contenga una etiqueta HTML.",
         "Guardar y abrir la ficha.",
         "Consultar el registro en PIM > Employee List."],
        "First Name: <b>Lucia</b>",
        "El texto se muestra literalmente, tal y como se introdujo, sin interpretarse "
        "como marcado. Comprobación del escapado de salida.",
        "Alta", "Funcional negativo", "Conjetura de errores", "Pasa", "",
    ),
    # ---------------------------------------------------------------- Contact / Emergency / Dependents
    (
        "CP-029", "RF-23",
        "Los campos de teléfono no admiten letras",
        "Sesión iniciada como Admin. Ficha de empleado abierta.",
        ["Ir a la pestaña Contact Details.",
         "Introducir letras en el campo Mobile.",
         "Pulsar Save."],
        "Mobile: SEIS CINCO DOS",
        "Se muestra el mensaje «Allows numbers and only + - / ( )» y el valor no se "
        "guarda.",
        "Media", "Funcional negativo", "Particiones de equivalencia", "Pasa", "",
    ),
    (
        "CP-030", "RF-24",
        "El correo electrónico con formato inválido se rechaza",
        "Sesión iniciada como Admin. Ficha de empleado abierta.",
        ["Ir a la pestaña Contact Details.",
         "Introducir una dirección sin arroba en Work Email.",
         "Pulsar Save."],
        "Work Email: lucia.herrera.empresa.com",
        "Se muestra el mensaje «Expected format: admin@example.com» y el valor no se "
        "guarda.",
        "Media", "Funcional negativo", "Particiones de equivalencia", "Pasa", "",
    ),
    (
        "CP-031", "RF-25",
        "Alta, edición y borrado de un contacto de emergencia",
        "Sesión iniciada como Admin. Ficha de empleado abierta.",
        ["Ir a Emergency Contacts y pulsar Add.",
         "Rellenar nombre, relación y teléfono, y guardar.",
         "Editar el teléfono del contacto creado y guardar.",
         "Eliminar el contacto y confirmar."],
        "Nombre: Marta Herrera · Relación: Sister · Teléfono: 652489174",
        "El contacto se crea, la edición persiste tras recargar y el borrado lo "
        "elimina de la tabla previa confirmación.",
        "Alta", "Funcional / Smoke", "Transición de estados", "Pasa", "",
    ),
    (
        "CP-032", "RF-26, RN-01",
        "Una persona a cargo no admite fecha de nacimiento futura",
        "Sesión iniciada como Admin. Ficha de empleado abierta.",
        ["Ir a la pestaña Dependents y pulsar Add.",
         "Introducir nombre y relación Child.",
         "Introducir una fecha de nacimiento posterior a hoy.",
         "Pulsar Save."],
        "Nombre: Pablo Herrera · Date of Birth: 2035-06-01",
        "El sistema rechaza la fecha con un mensaje de validación, igual que en la "
        "ficha del empleado.",
        "Media", "Funcional negativo", "Conjetura de errores", "Falla", "BUG-008",
    ),
    # ---------------------------------------------------------------- Job / Salary / Report-to / Attachments
    (
        "CP-033", "RN-02",
        "La fecha de incorporación no puede ser anterior a la de nacimiento",
        "Sesión iniciada como Admin. El empleado tiene fecha de nacimiento informada.",
        ["Comprobar en Personal Details la fecha de nacimiento del empleado.",
         "Ir a la pestaña Job.",
         "Introducir una Joined Date anterior a esa fecha de nacimiento.",
         "Pulsar Save."],
        "Date of Birth: 1995-15-06 · Joined Date: 1980-01-10",
        "El sistema rechaza la combinación con un mensaje de coherencia entre fechas: "
        "nadie se incorpora antes de nacer.",
        "Media", "Funcional negativo", "Tabla de decisión", "Falla", "BUG-009",
    ),
    (
        "CP-034", "RF-28, RN-03",
        "El importe salarial no admite valores negativos",
        "Sesión iniciada como Admin. Ficha de empleado abierta.",
        ["Ir a la pestaña Salary y pulsar Add.",
         "Seleccionar componente salarial, divisa y periodicidad.",
         "Introducir un importe negativo.",
         "Pulsar Save."],
        "Amount: -1500 · Currency: Euro · Pay Frequency: Monthly",
        "El sistema rechaza el importe con un mensaje de validación. Un salario "
        "negativo no es un dato posible.",
        "Alta", "Funcional negativo", "Valores límite", "Falla", "BUG-010",
    ),
    (
        "CP-035", "RF-29",
        "Un empleado no puede asignarse a sí mismo como supervisor",
        "Sesión iniciada como Admin. Ficha de empleado abierta.",
        ["Ir a la pestaña Report-to.",
         "En «Assigned Supervisors» pulsar Add.",
         "Introducir el nombre del propio empleado y seleccionarlo.",
         "Elegir el método de reporte y pulsar Save."],
        "Supervisor: el mismo empleado de la ficha",
        "El sistema impide la asignación: crea un ciclo en la jerarquía de "
        "supervisión.",
        "Media", "Funcional negativo", "Conjetura de errores", "Falla", "BUG-011",
    ),
    (
        "CP-036", "RF-30",
        "El adjunto que supera el tamaño máximo configurado se rechaza",
        "Sesión iniciada como Admin. Ficha de empleado abierta.",
        ["Ir a la sección Attachments de la ficha.",
         "Pulsar Add y seleccionar un fichero por encima del límite configurado.",
         "Introducir un comentario y pulsar Save."],
        "Fichero por encima del límite de subida de la instancia",
        "Se muestra un mensaje indicando el tamaño máximo permitido y el adjunto no "
        "se añade a la tabla.",
        "Media", "Funcional negativo", "Valores límite", "Bloqueado", "",
    ),
    # ---------------------------------------------------------------- Transversal
    (
        "CP-037", "RNF-01",
        "El listado de empleados es operativo en viewport móvil",
        "Sesión iniciada como Admin. DevTools en modo dispositivo 360 × 640.",
        ["Activar la emulación de dispositivo móvil a 360 × 640.",
         "Ir a PIM > Employee List.",
         "Desplegar el panel de filtros, buscar por Employee Id y revisar el resultado."],
        "Viewport: 360 × 640 (Galaxy S20)",
        "El menú lateral se colapsa, los filtros son accesibles y la tabla se consulta "
        "mediante desplazamiento horizontal sin perder columnas ni solaparse los "
        "controles.",
        "Media", "Responsive", "Particiones de equivalencia", "Pasa", "",
    ),
    (
        "CP-038", "RNF-03",
        "Los campos del formulario de alta tienen etiqueta asociada",
        "Sesión iniciada como Admin.",
        ["Ir a PIM > Add Employee.",
         "Recorrer el formulario completo usando únicamente la tecla Tab.",
         "Inspeccionar en las DevTools el marcado de cada input y su etiqueta.",
         "Comprobar en el árbol de accesibilidad el nombre expuesto de cada campo."],
        "Navegación por teclado + inspector de accesibilidad",
        "Cada campo es alcanzable por teclado en orden lógico y expone un nombre "
        "accesible mediante label asociado o aria-label.",
        "Media", "Accesibilidad", "Particiones de equivalencia", "Falla", "BUG-012",
    ),
]

COLUMNAS = [
    "ID", "Requisito asociado", "Título", "Precondiciones", "Pasos",
    "Datos de prueba", "Resultado esperado", "Prioridad", "Tipo",
    "Técnica de diseño", "Estado", "Defecto",
]
